#!/usr/bin/perl
##############################################################################
# Copyright © 2006-2010 Six Apart Ltd.
# This program is free software: you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details.  You should have received a copy of the GNU
# General Public License version 2 along with this program. If not, see
# <http://www.gnu.org/licenses/>

package SphinxSearch::GenSphinxConf;
use lib qw( lib extlib );

use base qw( MT::Tool );
use strict;
use warnings;

my $verbose;

my $bin_path;
my $file_path;
my $conf_path;

my $db_host;
my $db_user;
my $db_pass;

sub options {
    return (
        'verbose+'    => \$verbose,
        'bin_path=s'  => \$bin_path,
        'file_path=s' => \$file_path,
        'conf_path=s' => \$conf_path,
        'host=s'      => \$db_host,
        'user=s'      => \$db_user,
        'pass=s'      => \$db_pass,
    );
}

sub main {
    my $self = shift;
    ($verbose) = $self->SUPER::main(@_);
    my $plugin = MT::Plugin::SphinxSearch->instance;

    $plugin->set_config_value( 'sphinx_path', $bin_path, 'system' )
      if ($bin_path);
    $plugin->set_config_value( 'sphinx_file_path', $file_path, 'system' )
      if ($file_path);
    $plugin->set_config_value( 'sphinx_conf_path', $conf_path, 'system' )
      if ($conf_path);
    $plugin->set_config_value( 'db_host', $db_host, 'system' ) if ($db_host);
    $plugin->set_config_value( 'db_user', $db_user, 'system' ) if ($db_user);
    $plugin->set_config_value( 'db_pass', $db_pass, 'system' ) if ($db_pass);

    require SphinxSearch::Config;
    my $tmpl = SphinxSearch::Config->_gen_sphinx_conf_tmpl;
    my $str  = $tmpl->output;
    print "$str\n";
}

__PACKAGE__->main unless caller;
